### ISSUE TITLE
Support for other rule choices and/or partial Eclipse levels

### ISSUE THREAD

**Issue by DaltonGoesFast** [6thmoon/DifficultySelection#1]
Would it be possible to do make this mod work with all choices in the multiplayer lobby? Specifically with RulebookUnlocker by [Anreol].
What I'm looking to do is disable an item and the game remember what's disabled. 

Also would it be possible to add functionality to select only specific eclipse modifiers? like have E8 effect without E1-7 effects?

THANK YOU

**Comment by 6thmoon** [comment]
Hello, and thank you for your interest in this plugin. However, these features are a bit beyond the scope of what it is attempting to accomplish. Haven't tried these personally, but I would recommend checking out [**ContentDisabler**](https://thunderstore.io/package/William758/ContentDisabler/) and [**EclipseArtifacts**](https://thunderstore.io/package/Judgy/EclipseArtifacts) to see if they have the desired effect.

**Comment by 6thmoon** [comment]
If you're specifically looking for a standalone **E8** modifier, [**CurseCatcher**](https://thunderstore.io/package/6thmoon/CurseCatcher/) has a server-side *Artifact* that can be enabled in the configuration file. Haven't tested extensively, but it should work in multiplayer without requiring clients to have it installed.
